<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="container">
	<header role="banner">
		<div class="row labor-toolbar">
			<div class="col-md-3">
				<p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
			</div>
			<div class="col-md-9 labor-quick-access">
				<?php echo $this->getChildHtml('topLinks') ?>
				<?php echo $this->getChildHtml('store_language') ?>
			</div>
		</div>

		<div class="row">
			<div class="col-md-3">
				<h1 class="labor-logo">
					<div style="font-size: 28pt; padding-left: 65pt;">das labor</div>
					<div style="font-size: 80pt; margin-top: -20pt;">shop</div>
				</h1>
			</div>

			<div class="col-md-9">
				<?php echo $this->getChildHtml('topContainer'); ?>
				<?php echo $this->getChildHtml('topMenu') ?>
			</div>
		</div>
	</header>
</div>
