<?php
	$_productCollection = array_slice($this->getLoadedProductCollection()->getItems(),0,3);
	$_helper = $this->helper('catalog/output');
?>
<?php if(!count($_productCollection)): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="row labor-featured">
	<h2>Featured Products</h2>
	<?php foreach($_productCollection as $_product): ?>
		<div class="col-lg-4">
			<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
				<img class="labor-product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
			</a>
			<h3><?php echo $_productNameStripped; ?>
				<?php echo $this->getPriceHtml($_product, true) ?>
			</h3>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>
